import Head from "next/head";
import Kanban from "@/features/kanban";
import { Inter } from 'next/font/google'
import type { RootState } from '../store/index'
// import { useSelector, useDispatch } from 'react-redux'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const todo = useSelector((state: RootState) => state.todo.value)
  // const dispatch = useDispatch()

  
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
      <Kanban/>
      </main>
    </>
  );
}
