import Head from "next/head";
import Kanban from "@/features/kanban";
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export default function Home() { 
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,200,0,0" />
      </Head>
      <main className={inter.className}>
      <Kanban/>
      </main>
    </>
  );
}
